### ISSUE TITLE
Fix crawlers

### ISSUE THREAD

**Issue by RoySegall** [nirgn975/open-pension-crawler#28]
Crawlers are not working:
* [x] as-invest

**Comment by liat115** [comment]
https://stackoverflow.com/questions/33770129/how-do-i-disable-the-ssl-check-in-python-3-x

**Comment by RoySegall** [comment]
Checking why `as-invest` fails for now and it's a lot of a mess on the screen. Using:
`scrapy crawl as-invest -o as-invest.json --pdb --nolog`

will give me a debugger. The reason why is because of 
> urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

**Comment by RoySegall** [comment]
@nirgn975 Give me a merge commit.
