### ISSUE TITLE
Some more config stuff.

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/open-pension-crawler#3]
I don't have the pension we'll begin with yet (Ophir not responded to the email yet).

For now, I want to add `code sniffer` to run in [Travis-CI](https://travis-ci.org/) and check for each of the commits that we write good code (good code as define by [PEP 8](https://www.python.org/dev/peps/pep-0008/)).

You can see I add `pycodestyle` in [open_pension .travis.yml file](https://github.com/hasadna/open_pension/blob/master/.travis.yml). There is more stuff there but you only need the `code sniffer` stuff. So take only what in `$TRAVIS_PYTHON_VERSION == 3.5` if statement.

You can see in [open_pension .travis.yml file](https://github.com/hasadna/open_pension/blob/master/.travis.yml) we use python 2.7 and 3.5 - you need only 3.5. And you don't need `postgresql` service.

Also, Let's Edit the `README.md` file and write some documentation on this project. You can take some inspiration from [open pension README.md file](https://github.com/hasadna/open_pension/blob/master/README.md) (click on the `Raw` button to see how it's written in markdown).

Don't forget to `checkout` back to `master` branch, do a `pull` and then `checkout` to a new branch (with `git checkout -b branchName`). Also, don't forget to open a PR after the first commit (if you still work on the PR write `WIP: ...` in the title), and if you have any question tag and ask me there (on the PR).

**Comment by daniellevi1** [comment]
@nirgn975 What the new path i need to put in code sniffer script like in open_pension/.travis.yml  file instead of that path 'server/pension/migrations'?

script:
  # Run code sniffer on the server directory.
- if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
  pycodestyle --show-source --max-line-length=119 --exclude=server/pension/migrations --show-pep8 server;
  fi

**Comment by nirgn975** [comment]
So the line

```
pycodestyle --show-source --max-line-length=119 --exclude=server/pension/migrations --show-pep8 server;
```

mean:
- to enable `pycodestyle`.
- to show the source of the error.
- to extend the max line length (PEP 8 say we can't write a line that's more 80 characters, but don't keep it, 119 is django default, and we don't have django here).
- to not check (exclude) the files in the path `server/pension/migrations`, we don't need this we don't have this path or those files.
- to show the PEP 8 that related to the error.
- `server` tell him to check the `server` directory, and we want to check the whole project, so put a dot (`.`) in there instead. 
- And you don't need the semicolon (`;`) at the end.

And of course you don't need all the `if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then` and `fi` at the end.

Also, I saw there is already a branch with a `commit`, so open a PR for him so I can read the code and comment on it.
And last thing, I forget to enable `Travis-CI`. I enable it now, so in your next commit it will actually run your code in the `.travis.yml` file (:

And if you want to put code in those comments use  one ` at the start and another one at the end (you can use this [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)).

**Comment by nirgn975** [comment]
@daniellevi1 
One more thing, let's also add `.gitignore` file in this PR. We can use a service to generate this file with [https://www.gitignore.io/](https://www.gitignore.io/), add there `python`, `osx`, `linux`, and `windows`.

Press on generate and you'll see the content that should be in our `.gitignore`. If you don't know what the file used for you can read about it in [here](https://git-scm.com/docs/gitignore).
