### ISSUE TITLE
Crawler

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/open-pension-crawler#4]
We'll start with [ילין לפידות](https://www.yl-invest.co.il/).
Write a basic crawler (or spider as it called in Scrapy) that just start with the website basic url (which is `https://www.yl-invest.co.il/`) and extract all `h1` headers.

Also, edit the "Installation" section on the `README.md` file. Add instructions on how to install the project, and start develop it (if someone will want to do a PR for us, he should know how to install it on his/her computer).

Check the [scrapy documentation](https://doc.scrapy.org/en/latest/) for help.
To extract all the `h1` in the page, use `XPath`.

**Comment by nirgn975** [comment]
@daniellevi1 Wait a little with this. I want to change it a bit, it looks to big for one PR.

**Comment by daniellevi1** [comment]
@nirgn975 It's cool I can do it, I just took a bit of reading on Spiders.

**Comment by nirgn975** [comment]
@daniellevi1 I don't have a doubt you'll do it. But it's not best practice to do a big PRs, it even make it harder for me to understand what is going on. Start reading on Spiders in the meanwhile, you'll need it for this PR.

**Comment by daniellevi1** [comment]
@nirgn975 Ok great

**Comment by isranumbers** [comment]
Pr that is too big can be an issue:

![image](https://cloud.githubusercontent.com/assets/2894490/19082249/fe12f0e4-8a65-11e6-8559-347b341330ea.png)

**Comment by nirgn975** [comment]
@daniellevi1 I edit the description, you can start work on this PR.

**Comment by daniellevi1** [comment]
OK, I'm on it
