### ISSUE TITLE
Sum inspiration 

### ISSUE THREAD

**Issue by isranumbers** [nirgn975/open-pension-crawler#6]
https://www.youtube.com/watch?v=S0gMOjjH2fw

(hope i didn't ruined anything yet)

**Comment by nirgn975** [comment]
LOL

In the meanwhile I'll keep this issue open for general purpose.

**Comment by nirgn975** [comment]
By the way, @daniellevi1 (Daniel) meet @isranumbers (Ophir). If you have any questions regarding the websites, the files, how and why they named like this feel free to open an issue, assign it to him, and ask him there (or maybe even on this issue, but tag him, so he will get a notification).

**Comment by isranumbers** [comment]
I'll just add that i'm not a programmer but an economist - so i'm more into the meaning behind the data files  (and also willing to help with stuff that needs a human analysis regarding the data).

**Comment by daniellevi1** [comment]
Great, thanks :)
